environment_config:
  path: constants/environment_config.dart
  class: Env

  fields:
    twitterClientId: 
      type: String
      env_var: TWITTER_CLIENT_ID
    twitterClientSecret:
      type: String
      env_var: TWITTER_CLIENT_SECRET
    admobBannerId:
      type: String
      env_var: ADMOB_BANNER_ID
    admobTestBannerId:
      type: String
      env_var: ADMOB_TEST_BANNER_ID
