environment_config:
  path: constants/environment_config.dart
  class: Env

  fields:
    admobBannerId:
      type: String
      env_var: ADMOB_BANNER_ID
    admobTestBannerId:
      type: String
      env_var: ADMOB_TEST_BANNER_ID
