name: sokutwi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2

  # DI
  flutter_riverpod: ^2.1.3
  riverpod: ^2.1.3
  # Router
  go_router: ^6.0.0
  # UI
  flutter_native_splash: ^2.2.16
  gap: ^2.0.1
  auto_size_text_field: ^2.1.0
  # Others
  twitter_api_v2: ^4.7.1
  twitter_oauth2_pkce: ^1.0.1
  freezed_annotation: ^2.2.0
  floor: ^1.4.1
  sqflite: ^2.2.2
  flutter_secure_storage: ^7.0.1
  flutter_portal: ^1.1.3
  path_provider: ^2.0.11
  share_plus: ^6.3.0
  csv: ^5.0.1
  file_picker:
    # TODO(Kurogoma4D): https://github.com/miguelpruivo/flutter_file_picker/issues/1208 がcloseしたらリリースバージョンに戻す
    git: https://github.com/tomk9/flutter_file_picker.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  environment_config: ^3.1.0
  go_router_builder: ^1.0.15
  build_runner: any
  build_verify: any
  freezed: ^2.2.0
  floor_generator: ^1.4.1

flutter:
  uses-material-design: true
  generate: true