name: sokutwi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2

  # DI
  flutter_riverpod: ^2.1.3
  riverpod: ^2.1.3
  # Router
  go_router: ^6.0.0
  # UI
  flutter_native_splash: ^2.2.16
  gap: ^2.0.1
  auto_size_text_field: ^2.1.0
  # Others
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^7.0.1
  flutter_portal: ^1.1.3
  path_provider: ^2.0.11
  share_plus: ^6.3.0
  csv: ^5.0.1
  file_picker:
    # TODO(Kurogoma4D): https://github.com/miguelpruivo/flutter_file_picker/issues/1208 がcloseしたらリリースバージョンに戻す
    git: https://github.com/tomk9/flutter_file_picker.git
  google_mobile_ads: ^2.3.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  environment_config: ^3.1.0
  go_router_builder: ^1.0.15
  build_runner: any
  build_verify: any
  freezed: ^2.2.0
  hive_generator: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1c1b1f"
  adaptive_icon_foreground: "assets/images/icon.png"
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#1c1b1f"
    theme_color: "#1c1b1f"

flutter_native_splash:
  color: "#1c1b1f"
  image: "assets/images/icon.png"
  color_dark: "#1c1b1f"
  fullscreen: true
  android_12:
    color: "#1c1b1f"
    image: "assets/images/icon.png"
