name: CD/Mobile

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'

      - name: Export current version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get dependencies
        run: flutter pub get

      - name: Generate l10n
        run: flutter gen-l10n

      - name: Configure Keystore
        env:
          ANDROID_KEY_FILE_BASE64: ${{ secrets.ANDROID_KEY_FILE_BASE64 }}
        run: |
          echo "$ANDROID_KEY_FILE_BASE64" | base64 -d > android/keystore.jks

      - name: Build Appbundle
        env:
          ADMOB_APP_ID: ${{ secrets.ADMOB_APP_ID }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASS: ${{ secrets.ANDROID_KEY_PASS }}
          ANDROID_KEY_STORE_PASS: ${{ secrets.ANDROID_KEY_STORE_PASS }}
        run: |
          flutter build appbundle --dart-define flavor=prod --build-number ${{ github.run_number }} 

      - name: Upload Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_CONSOLE_SERVICE_ACCOUNT }}
          releaseFiles: /build/app/outputs/bundle/release/app.aab
          packageName: dev.krgm4d.sokutwi
          track: production
          releaseName: ${{ env.RELEASE_VERSION }}
          status: completed
