name: CI/PullRequest

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'

      - name: Get dependencies
        run: flutter pub get

      - name: Generate l10n
        run: flutter gen-l10n
      
      - name: Generate env
        env:
          ADMOB_BANNER_ID: ${{ secrets.ADMOB_BANNER_ID }}
          ADMOB_TEST_BANNER_ID: ${{ secrets.ADMOB_TEST_BANNER_ID }}
        run: ./export_env.sh

      - name: Analyze
        run: flutter analyze
